
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5050/eureka


spring:
  application:
    name: Todo-service
  config:
    import: optional:configserver:http://localhost:4040
  datasource:
    url: jdbc:mysql://localhost:3306/TodaApp_DB
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com

  security:
    user:
      name: none
      password: none

server:
  port: 7070


