spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:4040

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Todo-Service
          uri: http://localhost:7070
          predicates:
            - Path=/api/v1/tasks/**
            - Path=/todo/**
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/account/**
            - Path=/auth/**

server:
  port: 6060

eureka:
  client:
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0
