
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://localhost:4040
  datasource:
    url: jdbc:mysql://localhost:3306/Authentication_DB
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: amr.elhady.programs@gmail.com
    password: rsrn irvh kxiy zxxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true