spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: Todo-service
              uri: http://localhost:7070
              predicates:
                - Path=/api/v1/tasks/**
                - Path=/todo/**
              filters:
                - StripPrefix=0
            - id: authentication-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/auth/**
                - Path=/api/v1/account/**
                - Path=/auth/**
              filters:
                - StripPrefix=0

server:
  port: 6060

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:5050/eureka
