
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5050/eureka

spring:
  application:
    name: Todo-service
  datasource:
    url: jdbc:mysql://localhost:3306/TodaApp_DB
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com

  security:
    user:
      name: none
      password: none

server:
  port: 7070


